# -*- coding: utf-8 -*-
"""DataExtraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rZIDsE4aRIsdyiUNxV4rFJZO9EHoKoP_
"""

import yfinance as yf
import pandas as pd
import os
import time
import random
import shutil
from google.colab import files

# İndirilecek hisseler
tickers = [
    'AAPL', 'MSFT', 'IBM', 'CSCO', 'NVDA', 'CRM',
    'JPM', 'GS', 'AXP', 'V',
    'AMZN', 'MCD', 'HD', 'NKE', 'DIS',
    'PG', 'KO', 'WMT',
    'MMM', 'BA', 'CAT', 'HON',
    'JNJ', 'MRK', 'AMGN', 'UNH',
    'CVX', 'VZ', 'SHW', 'TRV'
]

# Klasör oluştur
output_dir = "/content/djiastocks"
os.makedirs(output_dir, exist_ok=True)

# Tarih aralığı
start_date = '2000-01-01'
end_date = '2024-12-31'

# Her hisse için veri indir
for ticker in tickers:
    file_path = os.path.join(output_dir, f"{ticker}.csv")

    success = False
    attempts = 0

    while not success and attempts < 5:
        try:
            print(f"Downloading {ticker}... (attempt {attempts + 1})")

            # 🚨 HAM VERİLER İÇİN: auto_adjust=False
            df = yf.download(ticker, start=start_date, end=end_date, progress=False, auto_adjust=False)

            if df.empty:
                raise Exception("Empty data received, retrying...")

            # Tüm sütunları sakla (Adj Close dahil)
            df.index.name = 'Date'
            df.to_csv(file_path)
            print(f"{ticker} successfully saved")

            success = True

        except Exception as e:
            print(f"Error: {e}")
            attempts += 1
            time.sleep(random.uniform(10, 20))

    time.sleep(random.uniform(2, 5))

# ZIP dosyası olarak arşivle
shutil.make_archive("/content/djiastocks", 'zip', "/content/djiastocks")

# ZIP dosyasını indir
files.download("/content/djiastocks.zip")